#!/usr/bin/env python3
"""Check the declared environment and visible Python imports without running experiments."""

import argparse
import ast
import json
import os
from pathlib import PurePosixPath
import re
import subprocess
import sys
import tomllib


BASELINE = "environment/baseline.json"
LOCKFILE = "uv.lock"
PROJECT = "pyproject.toml"
INFRA = (".github/", "scripts/ci/", "tests/ci/")
SHARED_FILES = {"compose.yaml", "compose.yml", "docker-compose.yaml", "docker-compose.yml", ".dockerignore", ".gitattributes", ".python-version", "AGENTS.md", "dev.cmd", "dev.sh"}
CODE_SUFFIXES = {
    ".py", ".pyi", ".ipynb", ".sh", ".bash", ".bat", ".ps1",
    ".c", ".cc", ".cpp", ".cu", ".cuh", ".h", ".hpp", ".f", ".f90",
}


class PolicyError(Exception):
    pass


class GitSnapshot:
    def __init__(self, ref):
        self.ref = ref
        raw = subprocess.check_output(["git", "ls-tree", "-rz", ref])
        self.files = {
            item.split(b"\t", 1)[1].decode("utf-8")
            for item in raw.split(b"\0") if item
        }

    def read(self, path):
        return subprocess.check_output(
            ["git", "show", f"{self.ref}:{path}"], stderr=subprocess.PIPE
        ).decode("utf-8")


def package_name(value):
    return re.sub(r"[-_.]+", "-", value).lower()


def dependency_file(path):
    name = PurePosixPath(path).name.lower()
    return (
        name.startswith("dockerfile") or name.endswith(".dockerfile")
        or (name.startswith("requirements") and name.endswith((".txt", ".in", ".lock")))
        or name in {"pyproject.toml", "setup.py", "setup.cfg", "pipfile", "pipfile.lock", "poetry.lock", "uv.lock", "pdm.lock"}
        or (name.startswith(("environment", "conda")) and name.endswith((".yml", ".yaml")))
        or name in {"compose.yaml", "compose.yml", "docker-compose.yaml", "docker-compose.yml", "devcontainer.json"}
    )


def experiment_code(path):
    return (
        not path.startswith(("archive/", "docs/", "environment/", *INFRA))
        and path not in {"dev.cmd", "dev.sh"}
        and PurePosixPath(path).suffix.lower() in CODE_SUFFIXES
    )


def parse_lock(text):
    try:
        lock = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise PolicyError(f"Invalid {LOCKFILE}: {exc}") from exc
    if lock.get("version") != 1 or not isinstance(lock.get("package"), list):
        raise PolicyError("Use a native uv.lock generated by uv lock.")
    packages = {}
    for entry in lock["package"]:
        source = entry.get("source", {})
        if "virtual" in source:
            continue
        name, version = entry.get("name", ""), entry.get("version", "")
        if not isinstance(name, str) or not name or not isinstance(version, str) or not re.fullmatch(r"[0-9][A-Za-z0-9.!+_-]*", version):
            raise PolicyError("Every uv.lock dependency needs a name and exact version.")
        name = package_name(name)
        if name in packages and packages[name] != version:
            raise PolicyError(f"Conflicting locked versions for {name} in the shared profile.")
        artifacts = entry.get("wheels", []) + ([entry["sdist"]] if "sdist" in entry else [])
        if "registry" not in source or not artifacts or any(not re.fullmatch(r"sha256:[0-9a-fA-F]{64}", item.get("hash", "")) for item in artifacts):
            raise PolicyError(f"{name}: keep registry packages with SHA256 artifact hashes in uv.lock.")
        packages[name] = version
    if not packages:
        raise PolicyError("The frozen dependency lock is empty.")
    return packages


def imports_in(source, path):
    try:
        tree = ast.parse(source, filename=path)
    except SyntaxError as exc:
        raise PolicyError(f"Cannot parse {path}:{exc.lineno}: {exc.msg}") from exc
    imports, dynamic = set(), []
    importlib_names = {"importlib"}
    loader_names = {"__import__"}
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            importlib_names.update(alias.asname or alias.name for alias in node.names if alias.name == "importlib")
        elif isinstance(node, ast.ImportFrom) and node.module == "importlib" and node.level == 0:
            loader_names.update(alias.asname or alias.name for alias in node.names if alias.name == "import_module")
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.update(alias.name.split(".", 1)[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            imports.add(node.module.split(".", 1)[0])
        elif isinstance(node, ast.Call):
            target = node.func
            loader = (
                isinstance(target, ast.Name) and target.id in loader_names
            ) or (
                isinstance(target, ast.Attribute) and target.attr == "import_module"
                and isinstance(target.value, ast.Name) and target.value.id in importlib_names
            )
            if loader:
                if node.args and isinstance(node.args[0], ast.Constant) and isinstance(node.args[0].value, str):
                    name = node.args[0].value
                    if not name.startswith("."):
                        imports.add(name.split(".", 1)[0])
                else:
                    dynamic.append(f"{path}:{node.lineno}")
    return imports, dynamic


def check_cpu_container(snapshot, baseline, locked):
    if baseline.get("profile") != "cpu-development" or baseline.get("platform") != "linux/amd64":
        raise PolicyError("Use the shared cpu-development profile on linux/amd64.")
    image = baseline.get("base_image", "")
    if not re.fullmatch(r"\S+@sha256:[0-9a-fA-F]{64}", image):
        raise PolicyError("The base image must include an immutable @sha256 digest.")
    uv_image = baseline.get("uv_image", "")
    if not re.fullmatch(r"\S+@sha256:[0-9a-fA-F]{64}", uv_image):
        raise PolicyError("The uv image must include an immutable @sha256 digest.")
    accelerator = baseline.get("accelerator", {})
    if not isinstance(accelerator, dict) or accelerator.get("state") != "pending" or accelerator.get("backend") != "ascend":
        raise PolicyError("The CPU development profile must keep the Ascend platform pending.")
    if any(accelerator.get(key) is not None for key in ("device", "driver", "firmware", "cann", "pytorch", "torch_npu")):
        raise PolicyError("Do not declare unverified accelerator versions in the CPU development profile.")

    dockerfile = "environment/docker/Dockerfile"
    devcontainer = ".devcontainer/devcontainer.json"
    for path in (PROJECT, LOCKFILE, ".python-version", dockerfile, devcontainer, "compose.yaml", ".dockerignore", "environment/verify_environment.py", "environment/docker/entrypoint.sh", "dev.cmd", "dev.sh"):
        if path not in snapshot.files:
            raise PolicyError(f"Missing shared container file: {path}.")
    source = snapshot.read(dockerfile)
    aliases, images = set(), []
    for match in re.finditer(r"(?im)^FROM\s+(\S+)(?:\s+AS\s+(\S+))?\s*$", source):
        reference, alias = match.groups()
        if reference not in aliases:
            images.append(reference)
        if alias:
            aliases.add(alias)
    if images != [uv_image, image]:
        raise PolicyError("Dockerfile FROM must match the baseline's immutable uv and Python images.")
    if "uv sync --locked" not in source or "--all-groups" not in source:
        raise PolicyError("Install the native uv lock with uv sync --locked --all-groups.")
    if snapshot.read(".python-version").strip() != baseline["python"]:
        raise PolicyError(".python-version must match the exact baseline Python version.")
    try:
        project = tomllib.loads(snapshot.read(PROJECT))
    except tomllib.TOMLDecodeError as exc:
        raise PolicyError(f"Invalid {PROJECT}: {exc}") from exc
    if project.get("tool", {}).get("uv", {}).get("required-version") != "==" + baseline.get("uv", ""):
        raise PolicyError("pyproject.toml must pin the baseline uv version with required-version.")
    try:
        dev = json.loads(snapshot.read(devcontainer))
    except ValueError as exc:
        raise PolicyError(f"Invalid Dev Container configuration: {exc}") from exc
    if not isinstance(dev, dict) or dev.get("dockerComposeFile") != "../compose.yaml" or dev.get("service") != "dev":
        raise PolicyError("Dev Container must use the shared Compose dev service.")

def check(snapshot, changed, author, owner):
    owner_change = bool(owner) and author.casefold() == owner.casefold()
    protected = [
        path for path in changed
        if not path.startswith("archive/") and (
            path.startswith(("environment/", "configs/training/", ".devcontainer/"))
            or path in SHARED_FILES or dependency_file(path)
        )
    ]
    if protected and not owner_change:
        raise PolicyError("Only the repository owner may change the shared environment or training baseline: " + ", ".join(sorted(protected)))

    if BASELINE not in snapshot.files:
        raise PolicyError(f"Missing {BASELINE}; ask the maintainer to configure the shared baseline.")
    try:
        baseline = json.loads(snapshot.read(BASELINE))
    except (ValueError, UnicodeError) as exc:
        raise PolicyError(f"Invalid {BASELINE}: {exc}") from exc
    if not isinstance(baseline, dict) or baseline.get("schema_version") != 3:
        raise PolicyError("Unsupported environment baseline schema.")
    state = baseline.get("state")
    code = sorted(path for path in snapshot.files if experiment_code(path))
    if state == "pending":
        if code:
            raise PolicyError("The shared environment is not frozen. Experimental code must wait for the owner to configure it: " + ", ".join(code[:10]))
        return {"state": "pending", "message": "Structure/documentation changes only; no experimental environment has been frozen.", "python_files": 0, "dynamic_imports": []}
    if state != "frozen":
        raise PolicyError("Environment state must be pending or frozen.")
    if not re.fullmatch(r"\d+\.\d+\.\d+(?:[A-Za-z0-9.+-]+)?", baseline.get("python", "")):
        raise PolicyError("Set the exact Python version, including the patch version.")
    if not re.fullmatch(r"\d+\.\d+\.\d+", baseline.get("uv", "")):
        raise PolicyError("Set the exact uv version.")
    if LOCKFILE not in snapshot.files:
        raise PolicyError(f"Missing {LOCKFILE}.")
    locked = parse_lock(snapshot.read(LOCKFILE))
    check_cpu_container(snapshot, baseline, locked)

    extra = sorted(
        path for path in snapshot.files
        if not path.startswith(("archive/", *INFRA))
        and path not in {PROJECT, LOCKFILE, "compose.yaml", ".devcontainer/devcontainer.json", "environment/docker/Dockerfile"}
        and dependency_file(path)
    )
    if extra:
        raise PolicyError("Use the shared environment instead of separate dependency/Docker files: " + ", ".join(extra))
    aliases = baseline.get("import_map", {})
    if not isinstance(aliases, dict) or any(not isinstance(k, str) or not isinstance(v, str) for k, v in aliases.items()):
        raise PolicyError("import_map must map Python module names to locked package names.")
    for module, distribution in aliases.items():
        if package_name(distribution) not in locked:
            raise PolicyError(f"import_map entry {module} points to unlocked package {distribution}.")

    local_modules = set()
    for path in code:
        p = PurePosixPath(path)
        if p.suffix == ".py":
            local_modules.add(p.stem)
            local_modules.add(p.parts[0])
            if p.parts[0] == "src" and len(p.parts) > 1:
                local_modules.add(p.parts[1].removesuffix(".py"))
    standard = set(sys.stdlib_module_names) | set(sys.builtin_module_names) | {"__future__"}
    missing, dynamic, count = [], [], 0
    for path in code:
        if not path.endswith(".py"):
            continue
        count += 1
        imports, unresolved = imports_in(snapshot.read(path), path)
        dynamic.extend(unresolved)
        for module in sorted(imports):
            if module in standard or module in local_modules:
                continue
            distribution = aliases.get(module, module)
            if package_name(distribution) not in locked:
                missing.append(f"{path}: {module}")
    if missing:
        raise PolicyError("Imports outside the shared dependency lock: " + "; ".join(missing))
    return {"state": "frozen", "message": "Declared environment and visible Python imports match the shared baseline.", "python_files": count, "dynamic_imports": dynamic}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", default="")
    parser.add_argument("--head", default="HEAD")
    parser.add_argument("--author", required=True)
    parser.add_argument("--owner", required=True)
    args = parser.parse_args()
    base = args.base
    if not base or set(base) == {"0"}:
        base = subprocess.check_output(["git", "rev-parse", f"{args.head}^"], text=True).strip()
    changed = subprocess.check_output(
        ["git", "diff", "--name-only", "--no-renames", "-z", base, args.head]
    ).decode("utf-8").split("\0")
    try:
        result = check(GitSnapshot(args.head), [p for p in changed if p], args.author, args.owner)
    except PolicyError as exc:
        print(f"Environment policy failed: {exc}", file=sys.stderr)
        return 1
    print(json.dumps(result, ensure_ascii=False, indent=2))
    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with open(summary, "a", encoding="utf-8") as f:
            f.write(f"### Environment consistency\n\nState: **{result['state']}**\n\n{result['message']}\n")
            if result["dynamic_imports"]:
                f.write("\nDynamic imports need manual confirmation:\n" + "\n".join(f"- `{p}`" for p in result["dynamic_imports"]) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
